name: Markdown Links Check
# runs every monday at 9 am
on:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: [self-hosted, monkci-runners-4vcpu]
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@a996638015fbc9ef96beef1a41bbad7df8e06154
        # checks all markdown files from /docs including all subfolders
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
          folder-path: 'docs/'
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@a996638015fbc9ef96beef1a41bbad7df8e06154
        # checks all markdown files from root but ignores subfolders
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
          max-depth: 0

  up-to-date-with-chromium:
    runs-on: [self-hosted, monkci-runners-4vcpu]

    steps:
    - name: git clone
      uses: actions/checkout@v4
    - name: Use Node.js 22.19
      uses: actions/setup-node@v4
      with:
        node-version: '22.19'
    - run: yarn --frozen-lockfile

    - run: yarn mocha --testMatch=third-party/chromium-synchronization/*-test.js
